# NOTE: This test is entirely generated by Claude as of right now as a means of providing a skeleton to use as a starting point.
# It is entirely made under the assumption of a standard ROS2 Mission Control Node and is not adapated to any specific implementation.
# Accuracy or completeness is not guaranteed. Please review and modify as needed.

# NEED:
# Import actual Mission Control Node when it's available

import os
import pytest
import rclpy
import time

from rclpy.node import Node
from rclpy.executors import SingleThreadedExecutor

from re_rassor_interfaces.msg import LocationStatus
from launch import LaunchDescription
from launch_ros.actions import Node as LaunchNode
import launch_testing
import launch_testing.actions


def generate_test_description():
    mission_node = LaunchNode(
        package='mission_controller',
        executable='mission_controller_node',
        name='mission_controller',
        output='screen'
    )

    return LaunchDescription([
        mission_node,
        launch_testing.actions.ReadyToTest(),
    ]), {
        'mission_node': mission_node,
    }


@pytest.mark.launch_test
def test_status_published(mission_node, proc_output):
    """
    Check that the mission controller publishes a status message 
    when fed incoming position updates.
    """
    rclpy.init()

    test_node = Node("test_node")
    received = {}

    # subscriber to controller status
    def callback(msg):
        received['msg'] = msg

    sub = test_node.create_subscription(
        LocationStatus,
        "/mission_controller/status",
        callback,
        10
    )

    # publisher to feed position into controller
    pub = test_node.create_publisher(LocationStatus, '/location_status', 10)

    executor = SingleThreadedExecutor()
    executor.add_node(test_node)

    # Publish a fake location status
    msg = LocationStatus()
    msg.position_x = 1.0
    msg.position_y = 2.0
    msg.velocity = 1.1
    msg.orientation = 0.5

    start_time = time.time()
    while time.time() - start_time < 5.0 and 'msg' not in received:
        pub.publish(msg)
        executor.spin_once(timeout_sec=0.1)

    assert 'msg' in received, "Mission controller did not publish status"

    rclpy.shutdown()
